### ISSUE TITLE
Item immediately resells for the same price as it was purchased for?

### ISSUE THREAD

**Issue by 77kq** [h0nde/roblox-item-sniper#1]
Title explains bug, I managed to get an egg for 1R$ but it immediately sold to another snipe bot, and this account's cookie isn't attached to anything else that could be selling the items it gets...

![image](https://user-images.githubusercontent.com/79558107/108945618-e81f4700-762a-11eb-9062-b0b186f13352.png)
![image](https://user-images.githubusercontent.com/79558107/108945637-f53c3600-762a-11eb-994e-6691cf32b8fe.png)

**Comment by h0nde** [comment]
I've heard about this problem a couple years back, and I've just had somebody else complain about it a week ago.

This is a problem on Roblox's end and I am not aware of any ways around it.
