### ISSUE TITLE
xsrf update error: list index out of range <class 'IndexError'>

### ISSUE THREAD

**Issue by doggo1000** [h0nde/roblox-item-sniper#5]
This is outdated 

grab the xsrf from 

```
import requests

xsrfreq= requests.post('https://auth.roblox.com/v2/login', cookies={'.ROBLOSECURITY': COOKIE})
xsrf= xsrfreq.headers["x-csrf-token"]

```

change that where you update the xsrf

this is more reliable knowing roblox updates their page pretty often.

**Comment by h0nde** [comment]
This should've been already fixed, make sure you're running the latest version. https://github.com/h0nde/roblox-item-sniper/pull/2
